### PR TITLE
Add a General settings panel which includes a lot of org options

### PR DESCRIPTION
**Pull request by jcmorrow**
This is decently on the way to lining up with the designs in https://github.com/RecordReplay/devtools/issues/4575. It's not actually hooked up to the backend yet though 😅 

CleanShot 2021-11-23 at 20 21 18

### CODE REVIEW

**Review by jasonLaster — COMMENTED** [review]
It might take a bit of finagling to conditionally add the menu item, but then we can land this darkly with `app.features.generalSetting`

**Comment by jcmorrow** [comment]
> It might take a bit of finagling to conditionally add the menu item, but then we can land this darkly with `app.features.generalSetting`

True! Maybe a good plan would be to implement the Name and Logo fields (which can stay on for everyone) first, and feature-flag the org stuff until the rest of the backend changes are in?

**Comment by jasonLaster** [comment]
Yep! I like it

**Comment by jasonLaster** [comment]
Is this still relevant. It looks like it should be.

**Comment by jcmorrow** [comment]
Done in https://github.com/RecordReplay/devtools/pull/4704

**Pull request closed without merging**
