### PR TITLE
New 8px grid

### LINKED ISSUE #1883: [UX] Move to 8px grid (⚙ Code ready)
image

Left: production
Right: design guidance

We're going to modify other details in the comments, but let's first move to a nice and tight 8px grid as shown here.

Figma page: GUTE-2 8px grid

### PR DESCRIPTION
**Pull request by jaril**
Fix #1883.

Screenshot:
image

### CODE REVIEW

**Comment by jonbell-lot23** [comment]
Checking now...

**Comment by jasonLaster** [comment]
Slightly bigger gap at the top of the vertical line than the bottom. Other than that, it's great

Screen Shot 2021-03-02 at 6 51 45 PM

**Comment by jonbell-lot23** [comment]
Looks good to me once we get these lines extending further:
image

This will queue up some follow-on changes (like the grid looks like it needs more space on the left and right sides) but those can come later.

**Comment by jonbell-lot23** [comment]
(Lol, Jason and I said the same thing. ~~BRAINWAVES~~)

You rock, Jaril! Today's been crazy with all the updates.

**Pull request merged**
