### PR TITLE
Stick the progress bar to prevent losing when scrolling

### PR DESCRIPTION
**Pull request by johnathan-co**
@jaril 
#6459

### CODE REVIEW

**Comment by jaril** [comment]
@johnathan-co looks like there might be some funkiness around the progress bar being used in the editor with the sticky change.

Tried to capture it in this video — not sure if you'll see but for a split second it displays under line 1.

https://user-images.githubusercontent.com/15959269/164104503-84c7668e-4747-4d5f-939b-6cebbc6a553f.mov

**Comment by jaril** [comment]
Maybe we can create a separate style specifically just for the console?

**Comment by johnathan-co** [comment]
> Maybe we can create a separate style specifically just for the console?

We could and that was the route I was going to go when I _thought_ I saw some funkiness with the Elements tab.

**Review by jaril — CHANGES_REQUESTED** [review]
Looks like this sits well for all the other places that this component is being used in (console, network monitor, elements), but it throws things off in the code editor. 

Let's turn this `position: sticky` into a console specific style and i think we're good to go!

Let's make sticky a specifically

**Pull request merged**
