### PR TITLE
Granular invite links for teams

### PR DESCRIPTION
**Pull request by jonbell-lot23**
Hi @jaril ! I just did the front-end design for https://github.com/RecordReplay/devtools/issues/5334 and now I'm handing it over to you to make the checkboxes do the right things.

image

### CODE REVIEW

**Comment by jonbell-lot23** [comment]
@jaril I've done my part, now handing over to you

**Comment by jonbell-lot23** [comment]
See notes: I am handing this over to Jaril because my work is done

**Comment by jonbell-lot23** [comment]
Pinging @jaril , I think this got lost in the shuffle. See original task here: https://github.com/RecordReplay/devtools/issues/5334

**Comment by jaril** [comment]
Notes from call with Jon:
- talk about compliance angle with gideon re: open gates to anyone with the same domain
- full marks answer would be that the owner would get a confirmation email when joe@replay.io comes in, and say why they're getting this
- Make sure we have the chevron for team role dropdown
- We don't explain what a dev is and can do - we should invest in docs
- We default to developer ($$$$$) when adding somebody as a team member but we don't give them a heads up that it costs money!

**Comment by jaril** [comment]
Closing this for now since it's not being actively worked on.

**Pull request closed without merging**
