### PR TITLE
Fix video playback when switching modes

### PR DESCRIPTION
**Pull request by ryanjduffy**
## Issue

The video was being set up within graphics which cached the node. When switching between viewer and devtools, the node would be dropped and remounted breaking the cached node reference.

## Resolution

* Adds `videoNode` and `videoUrl` to redux so they can be updated across views
* Updates the `Video` class to pull the latest node from the store when executing a command

### CODE REVIEW

**Comment by kannanvijayan** [comment]
I tested this locally and it's basically working.  The only remaining issue seems to be if the user presses the video play button _before_ the full blob has been received and set as the video source.  If you hit play after that, things are fine.

I suspect that we can, at this point, try using media-stream APIs again to incrementally feed the data to the video element.

**Comment by jasonLaster** [comment]
It's probably simpler to just disable playing the video until everything has loaded

**Review by jasonLaster — APPROVED** [review]

**Comment by ryanjduffy** [comment]
Pushed an update that should retain video playback when swapping between views.

**Comment by ryanjduffy** [comment]
No clue why TS is failing on this PR. I didn't touch that file, I can't repro it locally, and I don't see where `userSettings` is required as a prop for `DevTools`. 🤷‍♂️

**Pull request merged**
