### PR TITLE
Standardize on 8px between horizontal panels

### PR DESCRIPTION
**Pull request by jcmorrow**
Fixes https://github.com/RecordReplay/devtools/issues/4360

After:

CleanShot 2021-11-16 at 08 06 39

CleanShot 2021-11-16 at 08 06 27

### CODE REVIEW

**Comment by jasonLaster** [comment]
4 feels a bit narrow, but tough to say

**Comment by jcmorrow** [comment]
Yeah, I sort of agree, that's why I initially had the handles as 8px. @jonbell-lot23 what do you think?

**Comment by jonbell-lot23** [comment]
@jcmorrow : I don't think 4px is too tight, but I am totally fine with 8px. The key is that they are consistent because we were juggling a lot of inconsistency before.

**Comment by jcmorrow** [comment]
I'm going to make it consistently 8px for now. If we want to change it to 4 in the future, that is easy to do!

**Pull request merged**
