### PR TITLE
Tweak onboarding hat copy

### PR DESCRIPTION
**Pull request by jonbell-lot23**
Fixes https://github.com/orgs/RecordReplay/projects/57/views/16?filterQuery=assignee%3A%40me+iteration%3A%40current&groupedBy%5BcolumnId%5D=Status&sortedBy%5Bdirection%5D=asc&sortedBy%5BcolumnId%5D=90677

Copying from the ticket -->

[Here's a Notion doc](https://www.notion.so/replayio/Hats-overview-c8fb98b59d744d5197cc7096fcb6e519) where I described before/after copy changes

Here are the new screens:

image

image

image

image

image

Previously we said "add a local variable" but it's not clear how to do that, or what variables in the demo they should be putting there. So I changed it to a more general "you can do this" message.

image

This is the part I'm most interested in upgrading. I want to be able to add unicorns, but that's too hacky for the code right now. So instead I'm adding a "learn more" link and making it feel more like the end of the tour.

### CODE REVIEW

**Comment by jasonLaster** [comment]
😍

**Comment by jonbell-lot23** [comment]
@jasonLaster not sure about these red Xs in my deployment checks. Do I need to modify anything? if it's a typescript issue (for example I'm using JSX in something that used to just be a simple string) I'll need help fixing it.

**Comment by jasonLaster** [comment]
yep something is bad cc @bvaughn

**Comment by bvaughn** [comment]
CI is showing some lint errors. I think the only _blocking_ one is this:
> src/devtools/client/debugger/src/components/Editor/Breakpoints/Panel/FirstEditNag.tsx:15:9
 15:9  high  Using target="_blank" without rel="noreferrer" (which implies rel="noopener") is a... .trunk/out/3s2.txt 

The fix for this is just to add the `rel="noreferrer"` attribute to the link 😄 

```js
<a
  href="https://www.notion.so/replayio/Print-statements-1dcf7c3a8414423aab122ea7c4a41661"
  rel="noreferrer"
  target="_blank"
>
  Learn more
</a>
```

**Comment by bvaughn** [comment]
I tried to push a fix but I don't seem to have permissions to push to Jon's branch, so...

```diff
diff --git a/src/devtools/client/debugger/src/components/Editor/Breakpoints/Panel/FirstEditNag.tsx b/src/devtools/client/debugger/src/components/Editor/Breakpoints/Panel/FirstEditNag.tsx
index 02ba18d43..04aab9914 100644
--- a/src/devtools/client/debugger/src/components/Editor/Breakpoints/Panel/FirstEditNag.tsx
+++ b/src/devtools/client/debugger/src/components/Editor/Breakpoints/Panel/FirstEditNag.tsx
@@ -14,6 +14,7 @@ const TEXT = {
       <span className="flex grow justify-end">
         <a
           href="https://www.notion.so/replayio/Print-statements-1dcf7c3a8414423aab122ea7c4a41661"
+          rel="noreferrer"
           target="_blank"
         >
           Learn more
diff --git a/src/ui/components/shared/Nags/Nags.tsx b/src/ui/components/shared/Nags/Nags.tsx
index f0d0a2c0b..1ca9ec2d4 100644
--- a/src/ui/components/shared/Nags/Nags.tsx
+++ b/src/ui/components/shared/Nags/Nags.tsx
@@ -15,7 +15,7 @@ function NagHat({
   subText,
   nagType,
 }: {
-  mainText: string;
+  mainText?: string;
   subText: string;
   nagType: Nag;
 }) {
@@ -39,7 +39,9 @@ function NagHat({
     >
       <MaterialIcon iconSize="xl">auto_awesome</MaterialIcon>
       <div className="flex flex-col overflow-hidden text-xs">
-        <div className="overflow-hidden overflow-ellipsis whitespace-pre">{mainText}</div>
+        {mainText ? (
+          <div className="overflow-hidden overflow-ellipsis whitespace-pre">{mainText}</div>
+        ) : null}
         <div className="overflow-hidden overflow-ellipsis whitespace-pre font-bold">{subText}</div>
       </div>
     </div>
```

**Comment by jonbell-lot23** [comment]
Thank you!

**Pull request merged**
