### PR TITLE
Make tabs scrollable horizontally

### PR DESCRIPTION
**Pull request by jaril**
Chrome:
image
Firefox:
image

https://share.descript.com/view/KDseaBY6Q7A

### CODE REVIEW

**Review by karina-y — COMMENTED** [review]
looks like the tabs are showing the pathname now as well instead of just the source file name

image

**Comment by jaril** [comment]
It appears that the same thing happens without the patch. 

@jasonLaster is there a reason for keeping the path there? We can either 1) leave it alone, 2) manage the overflow and limit the tab to some n pixels, or 3) get rid of the path altogether.

image

**Review by jasonLaster — APPROVED** [review]

**Comment by jasonLaster** [comment]
So we show pathnames to disambiguate tabs... The goal is only show them when we have two conflicting tabs with the same filename. I'd be happy getting rid of it though and just showing paths on hover...

**Review by karina-y — APPROVED** [review]

**Comment by jaril** [comment]
Two failing tests right before being merged: 
-`inspector-05` is intermittent and passes locally.
-`console_warp-02` is flakey, see #1298 

image

**Pull request merged**
