### PR TITLE
Nicer "copy link" experience

### PR DESCRIPTION
**Pull request by jonbell-lot23**
Here's a Loom showing the difference:
https://www.loom.com/share/68cc08d77a3d40dc9af8b0cb6b749d5f

### CODE REVIEW

**Review by jasonLaster — APPROVED** [review]
Nice work! What do you think about also showing the copy button when you hover on the title. I think this is pretty common.

**Comment by jonbell-lot23** [comment]
> Nice work! What do you think about also showing the copy button when you hover on the title? I think this is pretty common.

Totally -- do you mean doing the blue highlight when hovering on the title, or do you mean hiding the icon until you mouse over the title?

I considered the latter and decided against it because it's not discoverable, but I think the former sounds good. Only thing is I need to figure out how to do it :)

**Comment by jasonLaster** [comment]
@jonbell-lot23 we should probably step back and think through whether a copy button makes sense in this use case

1. it was never in any designs and i'm pretty sure Jaril added it primarily for testing purposes ([link](https://github.com/replayio/devtools/pull/7234))
2. the copy button currently copies the url for the test run, but that should already be the URL in the url bar. This is not currently the case, but I consider that a bug.
3. We do not currently have a copy button for internal replay links. If we were to do want to expose something like that it would typically be through an actions dropdown with a label explaining the action.

**Comment by jonbell-lot23** [comment]
Sounds good, easy to delete when it's not needed for testing!

**Pull request merged**
