### PR TITLE
Fix broken inspector test

### PR DESCRIPTION
**Pull request by jcmorrow**
I think this works?

### CODE REVIEW

**Review by jasonLaster — APPROVED** [review]
This is super strange

**Comment by jasonLaster** [comment]
seeing a TS error for DeclarationValue

**Comment by jcmorrow** [comment]
> This is super strange

Yeah. Also, if you want an example of something that was *really* difficult to debug, even with Replay, this is a good example. This was manifesting as a `Objects are not valid as a React child` error!

**Review by jasonLaster — APPROVED** [review]

**Comment by jasonLaster** [comment]
Yes! We should keep a document of hard to debug bugs!

**Comment by jasonLaster** [comment]
And yeah - i think i hit it locally too

https://app.replay.io/recording/fbb1bb91-149f-420f-8efa-9c63de32e816?point=19795631794575832568756173673595881&time=21189.11028610629&hasFrames=true

**Pull request merged**
