### PR TITLE
Focus Mode 1.1 UI tweaks

### PR DESCRIPTION
**Pull request by bvaughn**
Loom: https://www.loom.com/share/352cdf641fe147fea22d013772208e80

- [x] Focus toggle button has distinct on/off states now
- [x] Discard button is always enabled

### CODE REVIEW

**Review by jcmorrow — APPROVED** [review]
Love this. On a side-note: during your loom I noticed that the width of the timestamps jumps when you toggle Focus Mode selection on and off and now I can't unsee it 👀

**Comment by bvaughn** [comment]
> I noticed that the width of the timestamps jumps when you toggle Focus Mode selection on and off and now I can't unsee it 👀

Good catch! Let me look.

**Review by jonbell-lot23 — APPROVED** [review]
I noticed the timestamp jiggle also, so +1 to that.

Looking good! I wonder if the word "cancel" maybe fits better, but that's for me to muse on later, not something that would prevent this release

**Comment by bvaughn** [comment]
Had "Cancel" at one point locally and decided to go with "Discard" instead because that felt more like what you were doing (_discarding_ the focus region) – but I don't feel strongly about it!

**Comment by bvaughn** [comment]
As for the jiggled, I had noticed that at one point and meant to follow up on it but then I just...stopped seeing it 😅 

There's a 1 pixel width difference between the editable and non-editable state, despite my setting width and max-width, as well as border, margin, and padding to 0. I'll take another pass at it.

**Comment by bvaughn** [comment]
Fixed the jiggle https://www.loom.com/share/8f6445a6de60482d9266f2c546ecb477

**Pull request merged**
