### PR TITLE
Make the markup box fill its panel (#5044)

### PR DESCRIPTION
**Pull request by hbenl**
Before:
Screenshot from 2022-01-19 16-11-10

After:
Screenshot from 2022-01-19 16-17-05

### CODE REVIEW

**Comment by abstractalgo** [comment]
Not a desired behavior (notice empty space on the right).

https://user-images.githubusercontent.com/1355455/150182942-c9c4a849-17fb-4aba-86ce-a96b18e95c1b.mp4

**Review by abstractalgo — CHANGES_REQUESTED** [review]
Not a desired behavior (notice empty space on the right).

https://user-images.githubusercontent.com/1355455/150182942-c9c4a849-17fb-4aba-86ce-a96b18e95c1b.mp4

**Comment by hbenl** [comment]
Thanks! So that's what the `width: fit-content` was doing there in the first place. Let's try with `min-width: fit-content` then.

**Review by abstractalgo — APPROVED** [review]
lgtm 👍

**Pull request merged**
