### PR TITLE
Add a progress bar for the editor and inspector

### LINKED ISSUE #1410: [UX] Add loading progress bars to panels
Today we use the word "loading..." in panels, as shown on these top two examples:

image

But a simple progress bar crawling along the top can go a long way towards making the UI feel responsive. That's my recommendation for now, and we'll look into more detailed approaches like illustrations and copy once this is in.

(We may find that the progress bar by itself is sufficient! We often found at Twitter that having a light touch like this was more than enough, and extra words/images were a bit much)

This issue is also related to the breakpoints widget. ([Issue #1402](https://github.com/RecordReplay/devtools/issues/1402))

### PR DESCRIPTION
**Pull request by jaril**
Fix #1410.

Good recording to test this on: https://share.descript.com/view/QN97TvnaWpq

Demo: https://share.descript.com/view/f16rPx4hvUj

### CODE REVIEW

**Comment by jasonLaster** [comment]
Do we want to get rid of `Loading...` in the editor?

**Comment by jaril** [comment]
@jonbell-lot23 thoughts?

In the mock-up, we get rid of loading text for both the editor and elements, and replace it with the loading bar instead. 

I followed that for the elements/inspector. As for the editor, I didn't see an easy way to get rid of the loading text so I left it in for now. 

(As I'm typing this I just thought of a way to get rid of the editor loading text so that should be a trivial change)

**Review by jasonLaster — APPROVED** [review]

**Comment by jasonLaster** [comment]
yeah, this should do it...

```diff
diff --git a/src/devtools/client/debugger/src/utils/editor/source-documents.js b/src/devtools/client/debugger/src/utils/editor/source-documents.js
index 73218f70..7192ec9f 100644
--- a/src/devtools/client/debugger/src/utils/editor/source-documents.js
+++ b/src/devtools/client/debugger/src/utils/editor/source-documents.js
@@ -55,7 +55,7 @@ export function showLoading(editor) {
   } else {
     doc = editor.createDocument();
     setDocument("loading", doc);
-    doc.setValue("Loading\u2026");
+    doc.setValue("");
     editor.replaceDocument(doc);
     editor.setMode({ name: "text" });
```

**Comment by jonbell-lot23** [comment]
Ah one more thing, @jaril . Remember when we talked about the feeling of satisfaction when a bar animates all the way to the end? I want to make sure these panels don't load 40% then snap into place. I want it to show 40%, race to 100%, then load. If we do it fast enough it should only add .1 second but still provide that feeling of completion.

**Comment by jasonLaster** [comment]
This is a crazy example of how recording in replaying and discussing would
be nice

**Pull request merged**
