### PR TITLE
Removed border radius from unicorn badge

### PR DESCRIPTION
**Pull request by bvaughn**
I can't repro the border radius issue you emailed me about but does this fix it?

### CODE REVIEW

**Comment by jasonLaster** [comment]
Looks like we had a regression with the print statement badge color which used to be a darker grey
Screen Shot 2022-05-20 at 3 26 30 PM

Also the picker still has a border when no badge is selected. I think that is an SVG issue
Screen Shot 2022-05-20 at 3 26 21 PM

**Review by jonbell-lot23 — COMMENTED** [review]
1. Horn looks fixed!
2. As Jason mentioned, the little grey capsule got lost so we need to fix that.
3. The border we have on the picker is by design until we get a better icon design. It looks wrong with no border, so we can keep this way for now.

**Comment by bvaughn** [comment]
> Looks like we had a regression with the print statement badge color which used to be a darker grey

Oops! Thanks for catching this.

I think I misunderstood what the desired behavior was for that state. I'll push a fix before landing this change 😄

**Comment by bvaughn** [comment]
Going to land this to verify that the Vercel deployments are picking up from `main` okay.

**Comment by ryota-murakami** [comment]
@bvaughn Nice Work! 😄

**Pull request merged**
