### PR TITLE
Replay Info polish

### PR DESCRIPTION
**Pull request by jonbell-lot23**
**Changes in this PR**

1. Rename "Events" to "Replay Info"
2. Attach more accurate icon to Replay Info
3. Make the Replay Info icon first, since that's what we default to in most cases

Prod:
image

New:
image

### CODE REVIEW

**Review by jasonLaster — APPROVED** [review]
I like it!

It solves some of the bigger IA questions for me and feels controversial and obvious at the same time.

**Comment by jonbell-lot23** [comment]
> I like it!
> 
> It solves some of the bigger IA questions for me and feels controversial and obvious at the same time.

Lol, what a great comment. Thanks for the approval!

**Comment by gideonred** [comment]
FYI A lot of our docs refer to the "Events" icon. We'll need to update it all.

**Comment by jonbell-lot23** [comment]
> FYI A lot of our docs refer to the "Events" icon. We'll need to update it all.

Good call, thanks!

**Pull request merged**
