### PR TITLE
Add launch button to user options menu

### LINKED ISSUE #2335: Our download link should be dynamic
1. If you're using the Replay browser already, the link should go away
2. The link should say "Launch Replay" and launch the app if it's installed, otherwise take you to the install page

We should put a conditional in the Library dropdown so it's not in the library but still exists in the /view/ part of the product.

### PR DESCRIPTION
**Pull request by ryanjduffy**
Replaces "Download Replay" menu option with "Launch Replay" option that shows a modal to allow downloading if needed.

Fixed #2335

### CODE REVIEW

**Comment by ryanjduffy** [comment]
@jonbell-lot23 - I didn't replace the icon with the menu item yet. If you have suggestions, they're welcome!

**Comment by ryanjduffy** [comment]
Updated this to include the `launchBrowser` feature flag.

**Review by jaril — APPROVED** [review]
LGTM!

**Comment by jonbell-lot23** [comment]
Hey @ryanjduffy and @jaril sorry that I missed a step here, but I'm curious why this is behind a flag? We want to push it live for everyone, right?

**Comment by ryanjduffy** [comment]
@jasonLaster requested it but I suspect it's in part to get the browser update rolled out so the feature works for everyone.

**Comment by jonbell-lot23** [comment]
Ah ha, thanks!

**Pull request merged**
