### PR TITLE
users now able to reply to comments

### PR DESCRIPTION
**Pull request by karina-y**
- users are now able to reply to comments
- replies are only allowed from the transcript panel and not the timeline
- comment replies are only allowed on parent comments
- replies are not shown in the timeline
- when a parent comment is deleted, any replies it has are also deleted
- when a parent or child comment is selected, all become highlighted with a left border. replies however are highlighted with a lighter color to denote they are replies
- users are able to edit and delete replies

image

### CODE REVIEW

**Comment by karina-y** [comment]
i saw when requesting a review from @jasonLaster github added a note that he'd recently changed these files so i'm going to rebase master and retest. i will confirm when that's complete.

**Review by jasonLaster — APPROVED** [review]

**Comment by jasonLaster** [comment]
looks like

1. opening a reply
2. typing something
3. pressing cmd+enter 

will save the initial comment

**Comment by karina-y** [comment]
tests timing out in ci:
stepping-05 passes locally
inspector-02 times out locally and in master

**Comment by karina-y** [comment]
@jasonLaster 

i'm trying cmd+enter and it works fine on my end. is this what you were referring to (i'm hitting cmd+enter to save in this video)?
https://www.loom.com/share/0c5fa7dad45041a89c78de6e32025a32

**Comment by karina-y** [comment]
@jasonLaster replying from the parent and saving via cmd+enter now works. i'll let the tests run one more time then merge.

**Comment by karina-y** [comment]
tests timing out in ci are the same:
stepping-05 passes locally
inspector-02 times out locally and in master

**Pull request merged**
