### PR TITLE
Use custom auth0 hook everywhere

### LINKED ISSUE #4821: Can't comment when authenticated via API key
This is affecting QA Wolf and E2E testing

### PR DESCRIPTION
**Pull request by ryanjduffy**
## Issue

Fixes #4821 

## Resolution

There were a few places where we were using the stock `useAuth0` hook rather than our custom wrapper which means that some of our special handling for auth via API keys or the e2e test identity do not work.

### CODE REVIEW

**Review by jcmorrow — APPROVED** [review]
Oh my gosh, thank you! I was kicking myself trying to figure out why auth was failing in some tests! Great find!

**Comment by jasonLaster** [comment]
That's so tricky!

**Comment by ryanjduffy** [comment]
But wait ... there's more ... Seems like the tiptap editor doesn't pick up the new auth state because the extensions are created before the auth state is known and aren't updated when the auth state lands.

**Comment by ryanjduffy** [comment]
@jcmorrow - Mind giving this another look? Any concerns with bailing on rendering the editor?

**Comment by jcmorrow** [comment]
> @jcmorrow - Mind giving this another look? Any concerns with bailing on rendering the editor?

Yeah, if we don't absolutely have to `return null` there it would be great not to. I kind of like the current flow which is click to reply -> get asked to login. Right now this happens on the preview branch:

https://user-images.githubusercontent.com/5903784/146281005-8c068a29-8804-4cd3-af70-922c98f8f528.mp4

**Comment by ryanjduffy** [comment]
:+1: I missed that it would drop the "Reply". I'll check it out again.

**Review by jcmorrow — APPROVED** [review]
🚢

**Pull request merged**
