### PR TITLE
Devtools component panel

### PR DESCRIPTION
**Pull request by jasonLaster**

### CODE REVIEW

**Comment by jasonLaster** [comment]
The react devtools can be enabled by evaluating `app.features.reactDevtools = true` in the console and refreshing

**Comment by bvaughn** [comment]
FYI looks like your branch was a bit old (didn't have e630cca058cdc730b7e645e4477684f20fa87199)

**Comment by bvaughn** [comment]
Also just to connect these two efforts: https://github.com/facebook/react/pull/21032

**Comment by jasonLaster** [comment]
yep -- just fixed 🤦

**Pull request merged**
