### PR TITLE
Add feature flag to disable creating teams

### PR DESCRIPTION
**Pull request by ryanjduffy**
## Summary

* Adds support for `create-workspace-enabled` flag to disable creating a team from:
  * the library
  * the team leader onboarding flow

image
image

### CODE REVIEW

**Comment by jonbell-lot23** [comment]
Hey @ryanjduffy, one addition: instead of "Ok, sounds good" let's change the button to "Join the waitlist" and target our waitlist. Thanks!

**Comment by ryanjduffy** [comment]
Do you want to have an opt-out button as well? I think on the onboarding modal, we need some way to continue the flow. In the create a team modal, we could possibly get away without another button because the user can click out to close the modal.

**Comment by jonbell-lot23** [comment]
Ah, good point. For the onboarding flow it should be

[Join Waiting List] [Skip]

Skip is easy.
Join waiting list should should load the form, which will be an overlay from the right side. Then when you're done with that, it'd be nice if it returned you to the next step in the onboarding. Is that doable?

**Comment by ryanjduffy** [comment]
We'll see! At a minimum, we can open a new tab with the form and then the user could return to continue.

**Pull request closed without merging**
