### PR TITLE
Deploy new focus mode icon

### PR DESCRIPTION
**Pull request by jonbell-lot23**
Was:
image

Now:
image

Was:
image

Now:
image

Was:
image

Now:
image

--

Notice that the foreground colour used to be white, and now it's black. We can go back to white, I just had trouble getting it working.

Also note that a new Global Loader design is coming, so we don't need to get too fancy with this just yet. This is in prep for that.

### CODE REVIEW

**Review by bvaughn — APPROVED** [review]
The new icon is a much better fit for focus!

I'm surprised to see the foreground color changed from white to black on the focus button! I guess it is a much better contrast ratio though.

CI was failing because of LInt errors so I went ahead and fixed them.

**Comment by jonbell-lot23** [comment]
"Notice that the foreground colour used to be white, and now it's black. We can go back to white, I just had trouble getting it working."

Cc @bvaughn

**Comment by bvaughn** [comment]
Yeah, so this is an issue where our Tailwind and theme colors don't really work well. I think we need to create some new Tailwind styles for toggle on/of background and foreground colors. I'll do that this afternoon at some point.

**Comment by bvaughn** [comment]
#6740

**Pull request merged**
