### PR TITLE
Migrate `client/commands` to TS

### PR DESCRIPTION
**Pull request by markerikson**
This is a precursor to work for #6591 .  I was browsing the code to see where some of the analysis logic is used, and kept tracing through `client/commands.js`, couldn't see what the args were or what code was used, and decided to migrate it.

This PR:

- Migrates `client/commands.js` to TS
  - Actually added types to client/commands
  - Deleted many functions that appear to be entirely dead (anecdotally confirmed by Jason)
  - Removed watchpoints logic in Scopes.js that appears to be dead
  - Removed irrelevant `setupCommands` function
- Migrates `client/index.js` to TS

### CODE REVIEW

**Comment by markerikson** [comment]
All the E2E tests have failed, but this seems to be something that's occurring in other PRs today like #6854 .

**Review by hbenl — CHANGES_REQUESTED** [review]
The reason for the e2e test failures is that you removed the resume/stepIn/stepOver/stepOut/rewind/reverseStepOver commands which are kinda central to a debugger.

> All the E2E tests have failed, but this seems to be something that's occurring in other PRs today like #6854 .

In that PR I only see one test failing, unlike this PR. Please don't ignore e2e test failures anymore, the tests have become more stable and since they have recordings (which are easily accessible from the [Summary page](https://github.com/RecordReplay/devtools/actions/runs/2354674729) for the "Run test suites" action) it's easy to investigate them.

**Comment by markerikson** [comment]
Hmm. I did remove those functions, but based on my initial searches only the _action creators_ with the same names were used.

But yeah, let me go back and review the changes.

**Comment by hbenl** [comment]
I *think* this is where they are used:
https://github.com/RecordReplay/devtools/blob/82a00fe58eb4421f4fef071cb8365b82adf2bd0e/src/devtools/client/debugger/src/actions/pause/commands.js#L43

**Comment by markerikson** [comment]
AHHH, I think I see the problem.

Yeah, these functions aren't used _in the app code_, but they _are_ exposed as globals and used in some of the test harness:

```js
  getVarsForTests() {
    assert(this.isReady, "DebuggerPanel not ready");
    return {
      store: this._store,
      selectors: this._selectors,
      actions: this._actions,
      client: this._client,
    };
  }

// snip
const dbgSelectors = {};
for (const [name, method] of Object.entries(dbg.selectors)) {
  dbgSelectors[name] = (...args) => method(dbg.store.getState(), ...args);
}
```

so yeah, I was right about the UI not using these, but apparently these are critical for tests.

Oooo-kay, reverting those changes...

**Comment by hbenl** [comment]
> so yeah, I was right about the UI not using these, but apparently these are critical for tests.

No, they're also used by the UI: when you view a recording with the preview deployment of this PR, the stepping buttons in the debugger are broken.

**Comment by markerikson** [comment]
@hbenl oh drat, you may be right there as well.  Lovely.

(also, there were other test failures yesterday due to Node 16 getting rolled out until Brian H reverted that, which is part of what was confusing me here)

**Comment by markerikson** [comment]
okay, gonna discard all the changes to `commands.ts` and start over, with just the TS conversion part

**Comment by markerikson** [comment]
Well, it's _less_ broken. 3 E2E tests pass, 2 fail, and I think Holger said that test `breakpoints-07.js` has been failing due to #6870 .

**Pull request closed without merging**
