### PR TITLE
Remove unnecessary console logging

### PR DESCRIPTION
**Pull request by bvaughn**
These log statements are adding a lot of noise to the console unnecessarily. It's getting in the way of my local logs.

### CODE REVIEW

**Comment by markerikson** [comment]
I felt the same way, but @bhackett1024 specifically requested that we keep those for debugging purposes.

**Comment by bhackett1024** [comment]
I would like to keep these in, but I also feel like I'm the only one.  Can we gate them behind a setting maybe?  The LoadedRegions one especially is handy for understanding precisely what the backend is doing.

**Comment by bvaughn** [comment]
Seems odd to me to leave console logging on for everyone for a niche use case like this. Can we maybe move it behind a flag and at least log to `console.debug` so I can hide it by turning off "verbose" logging? :)

**Comment by bvaughn** [comment]
Also which file(s) are we talking about? all of them?

**Comment by bhackett1024** [comment]
> Seems odd to me to leave console logging on for everyone for a niche use case like this. Can we maybe move it behind a flag or at least log to `console.debug` so I can hide it by turning off "verbose" logging? :)

Sure either of these is fine.  Deleting the logs besides the LoadedRegions one is also fine.

**Comment by bvaughn** [comment]
Great! I'm happy with that :) I'll remove the other two and change the loaded regions one to `console.debug` so it's there, but hidden by default :)

**Pull request merged**
